/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DomstateChild {
    }
    interface ReducerChild {
    }
    interface StateChild {
    }
    interface TestChild {
    }
    interface TestComponent {
        "provided": number;
        "start": number;
    }
}
declare global {
    interface HTMLDomstateChildElement extends Components.DomstateChild, HTMLStencilElement {
    }
    var HTMLDomstateChildElement: {
        prototype: HTMLDomstateChildElement;
        new (): HTMLDomstateChildElement;
    };
    interface HTMLReducerChildElement extends Components.ReducerChild, HTMLStencilElement {
    }
    var HTMLReducerChildElement: {
        prototype: HTMLReducerChildElement;
        new (): HTMLReducerChildElement;
    };
    interface HTMLStateChildElement extends Components.StateChild, HTMLStencilElement {
    }
    var HTMLStateChildElement: {
        prototype: HTMLStateChildElement;
        new (): HTMLStateChildElement;
    };
    interface HTMLTestChildElement extends Components.TestChild, HTMLStencilElement {
    }
    var HTMLTestChildElement: {
        prototype: HTMLTestChildElement;
        new (): HTMLTestChildElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "domstate-child": HTMLDomstateChildElement;
        "reducer-child": HTMLReducerChildElement;
        "state-child": HTMLStateChildElement;
        "test-child": HTMLTestChildElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface DomstateChild {
    }
    interface ReducerChild {
    }
    interface StateChild {
    }
    interface TestChild {
    }
    interface TestComponent {
        "provided"?: number;
        "start"?: number;
    }
    interface IntrinsicElements {
        "domstate-child": DomstateChild;
        "reducer-child": ReducerChild;
        "state-child": StateChild;
        "test-child": TestChild;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "domstate-child": LocalJSX.DomstateChild & JSXBase.HTMLAttributes<HTMLDomstateChildElement>;
            "reducer-child": LocalJSX.ReducerChild & JSXBase.HTMLAttributes<HTMLReducerChildElement>;
            "state-child": LocalJSX.StateChild & JSXBase.HTMLAttributes<HTMLStateChildElement>;
            "test-child": LocalJSX.TestChild & JSXBase.HTMLAttributes<HTMLTestChildElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
