/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CallbacksTest {
    }
    interface DomstateChild {
    }
    interface EffectTest {
    }
    interface InnocentChild {
    }
    interface KillerParent {
    }
    interface MemoChild {
    }
    interface NullLifecycleTest {
    }
    interface ReducerChild {
    }
    interface RefChild {
    }
    interface StateChild {
    }
    interface StateEffectChild {
    }
    interface TestChild {
    }
    interface TestComponent {
        "provided": number;
        "start": number;
    }
}
declare global {
    interface HTMLCallbacksTestElement extends Components.CallbacksTest, HTMLStencilElement {
    }
    var HTMLCallbacksTestElement: {
        prototype: HTMLCallbacksTestElement;
        new (): HTMLCallbacksTestElement;
    };
    interface HTMLDomstateChildElement extends Components.DomstateChild, HTMLStencilElement {
    }
    var HTMLDomstateChildElement: {
        prototype: HTMLDomstateChildElement;
        new (): HTMLDomstateChildElement;
    };
    interface HTMLEffectTestElement extends Components.EffectTest, HTMLStencilElement {
    }
    var HTMLEffectTestElement: {
        prototype: HTMLEffectTestElement;
        new (): HTMLEffectTestElement;
    };
    interface HTMLInnocentChildElement extends Components.InnocentChild, HTMLStencilElement {
    }
    var HTMLInnocentChildElement: {
        prototype: HTMLInnocentChildElement;
        new (): HTMLInnocentChildElement;
    };
    interface HTMLKillerParentElement extends Components.KillerParent, HTMLStencilElement {
    }
    var HTMLKillerParentElement: {
        prototype: HTMLKillerParentElement;
        new (): HTMLKillerParentElement;
    };
    interface HTMLMemoChildElement extends Components.MemoChild, HTMLStencilElement {
    }
    var HTMLMemoChildElement: {
        prototype: HTMLMemoChildElement;
        new (): HTMLMemoChildElement;
    };
    interface HTMLNullLifecycleTestElement extends Components.NullLifecycleTest, HTMLStencilElement {
    }
    var HTMLNullLifecycleTestElement: {
        prototype: HTMLNullLifecycleTestElement;
        new (): HTMLNullLifecycleTestElement;
    };
    interface HTMLReducerChildElement extends Components.ReducerChild, HTMLStencilElement {
    }
    var HTMLReducerChildElement: {
        prototype: HTMLReducerChildElement;
        new (): HTMLReducerChildElement;
    };
    interface HTMLRefChildElement extends Components.RefChild, HTMLStencilElement {
    }
    var HTMLRefChildElement: {
        prototype: HTMLRefChildElement;
        new (): HTMLRefChildElement;
    };
    interface HTMLStateChildElement extends Components.StateChild, HTMLStencilElement {
    }
    var HTMLStateChildElement: {
        prototype: HTMLStateChildElement;
        new (): HTMLStateChildElement;
    };
    interface HTMLStateEffectChildElement extends Components.StateEffectChild, HTMLStencilElement {
    }
    var HTMLStateEffectChildElement: {
        prototype: HTMLStateEffectChildElement;
        new (): HTMLStateEffectChildElement;
    };
    interface HTMLTestChildElement extends Components.TestChild, HTMLStencilElement {
    }
    var HTMLTestChildElement: {
        prototype: HTMLTestChildElement;
        new (): HTMLTestChildElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "callbacks-test": HTMLCallbacksTestElement;
        "domstate-child": HTMLDomstateChildElement;
        "effect-test": HTMLEffectTestElement;
        "innocent-child": HTMLInnocentChildElement;
        "killer-parent": HTMLKillerParentElement;
        "memo-child": HTMLMemoChildElement;
        "null-lifecycle-test": HTMLNullLifecycleTestElement;
        "reducer-child": HTMLReducerChildElement;
        "ref-child": HTMLRefChildElement;
        "state-child": HTMLStateChildElement;
        "state-effect-child": HTMLStateEffectChildElement;
        "test-child": HTMLTestChildElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface CallbacksTest {
    }
    interface DomstateChild {
    }
    interface EffectTest {
    }
    interface InnocentChild {
    }
    interface KillerParent {
    }
    interface MemoChild {
    }
    interface NullLifecycleTest {
    }
    interface ReducerChild {
    }
    interface RefChild {
    }
    interface StateChild {
    }
    interface StateEffectChild {
    }
    interface TestChild {
    }
    interface TestComponent {
        "provided"?: number;
        "start"?: number;
    }
    interface IntrinsicElements {
        "callbacks-test": CallbacksTest;
        "domstate-child": DomstateChild;
        "effect-test": EffectTest;
        "innocent-child": InnocentChild;
        "killer-parent": KillerParent;
        "memo-child": MemoChild;
        "null-lifecycle-test": NullLifecycleTest;
        "reducer-child": ReducerChild;
        "ref-child": RefChild;
        "state-child": StateChild;
        "state-effect-child": StateEffectChild;
        "test-child": TestChild;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "callbacks-test": LocalJSX.CallbacksTest & JSXBase.HTMLAttributes<HTMLCallbacksTestElement>;
            "domstate-child": LocalJSX.DomstateChild & JSXBase.HTMLAttributes<HTMLDomstateChildElement>;
            "effect-test": LocalJSX.EffectTest & JSXBase.HTMLAttributes<HTMLEffectTestElement>;
            "innocent-child": LocalJSX.InnocentChild & JSXBase.HTMLAttributes<HTMLInnocentChildElement>;
            "killer-parent": LocalJSX.KillerParent & JSXBase.HTMLAttributes<HTMLKillerParentElement>;
            "memo-child": LocalJSX.MemoChild & JSXBase.HTMLAttributes<HTMLMemoChildElement>;
            "null-lifecycle-test": LocalJSX.NullLifecycleTest & JSXBase.HTMLAttributes<HTMLNullLifecycleTestElement>;
            "reducer-child": LocalJSX.ReducerChild & JSXBase.HTMLAttributes<HTMLReducerChildElement>;
            "ref-child": LocalJSX.RefChild & JSXBase.HTMLAttributes<HTMLRefChildElement>;
            "state-child": LocalJSX.StateChild & JSXBase.HTMLAttributes<HTMLStateChildElement>;
            "state-effect-child": LocalJSX.StateEffectChild & JSXBase.HTMLAttributes<HTMLStateEffectChildElement>;
            "test-child": LocalJSX.TestChild & JSXBase.HTMLAttributes<HTMLTestChildElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
